# Generated by Django 3.0.2 on 2025-03-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMCModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdSpend', models.FloatField()),
                ('ClickThroughRate', models.FloatField()),
                ('ConversionRate', models.FloatField()),
                ('WebsiteVisits', models.FloatField()),
                ('PagesPerVisit', models.FloatField()),
                ('TimeOnSite', models.FloatField()),
                ('SocialShares', models.FloatField()),
                ('EmailOpens', models.FloatField()),
                ('EmailClicks', models.FloatField()),
                ('PreviousPurchases', models.FloatField()),
                ('LoyaltyPoints', models.FloatField()),
                ('CampaignType_Consideration', models.FloatField()),
            ],
        ),
    ]
